name: Run on label or comment

on:
  issue_comment:
    types:
      - "created"

jobs:
  Run_benchmarks:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'benchmark'}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout benchmarks
        uses: actions/checkout@v3
        with:
          repository: smithdc1/django-asv
          path: "."
      - name: Change to repo
        run: ls
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Cache Django
        uses: actions/cache@v3
        with:
          path: Django/*
          key: Django
      - name: Run Benchmarks
        shell: bash -l {0}
        run: |-
          asv machine --machine ubuntu-22.04 --yes
          set +e
          echo '```' >> $GITHUB_STEP_SUMMARY
          asv continuous --interleave-processes -a processes=2 --split --show-stderr 'HEAD^' 'HEAD' |\
          sed -n -E '/(before.*after.*ratio)|(BENCHMARKS)/,$p' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          set -e
